GO
INSERT INTO [dbo].[BeerStyles] ([Name]) VALUES
('American Light Lager'),
('American Lager'),
('Cream Ale'),
('American Wheat Beer'),
('International Pale Lager'),
('International Amber Lager'),
('International Dark Lager'),
('Czech Pale Lager'),
('Czech Premium Pale Lager'),
('Czech Amber Lager'),
('Czech Dark Lager'),
('Munich Helles'),
('Festbier'),
('Helles Bock'),
('German Leichtbier'),
('Kölsch'),
('German Helles Exportbier'),
('German Pils'),
('Märzen'),
('Rauchbier'),
('Dunkles Bock'),
('Vienna Lager'),
('Altbier'),
('Kellerbier'),
('Amber Kellerbier'),
('Munich Dunkel'),
('Schwarzbier'),
('Doppelbock'),
('Eisbock'),
('Baltic Porter'),
('Weissbier'),
('Dunkles Weissbier'),
('Weizenbock'),
('Ordinary Bitter'),
('Best Bitter'),
('Strong Bitter'),
('British Golden Ale'),
('Australian Sparkling Ale'),
('English IPA'),
('Dark Mild'),
('British Brown Ale'),
('English Porter'),
('Scottish Light'),
('Scottish Heavy'),
('Scottish Export'),
('Irish Red Ale'),
('Irish Stout'),
('Irish Extra Stout'),
('Sweet Stout'),
('Oatmeal Stout'),
('Tropical Stout'),
('Foreign Extra Stout'),
('British Strong Ale'),
('Old Ale'),
('Wee Heavy'),
('English Barleywine'),
('Blonde Ale'),
('American Pale Ale'),
('American Amber Ale'),
('California Common'),
('American Brown Ale'),
('American Porter'),
('American Stout'),
('Imperial Stout'),
('American IPA'),
('Belgian IPA'),
('Black IPA'),
('Brown IPA'),
('Red IPA'),
('Rye IPA'),
('White IPA'),
('Imperial IPA'),
('American Strong Ale'),
('American Barleywine'),
('Wheatwine'),
('Berliner Weisse'),
('Flanders Red Ale'),
('Oud Bruin'),
('Lambic'),
('Gueuze'),
('Fruit Lambic'),
('Witbier'),
('Belgian Pale Ale'),
('Bière de Garde'),
('Belgian Blond Ale'),
('Saison (pale) (standard)'),
('Saison (dark) (standard)'),
('Saison (pale) (table)'),
('Saison (pale) (super)'),
('Belgian Golden Strong Ale'),
('Trappist Single'),
('Belgian Dubbel'),
('Belgian Tripel'),
('Belgian Dark Strong Ale'),
('Gose'),
('Kentucky Common'),
('Lichtenhainer'),
('London Brown Ale'),
('Grodziskie'),
('Pre-Prohibition Lager'),
('Pre-Prohibition Porter'),
('Roggenbier'),
('Sahti'),
('Brett Beer'),
('Mixed-Fermentation Sour Beer'),
('Wild Specialty Beer'),
('Fruit Beer'),
('Fruit and Spice Beer'),
('Specialty Fruit Beer'),
('Spice, Herb, or Vegetable Beer'),
('Autumn Seasonal Beer'),
('Winter Seasonal Beer'),
('Alternative Grain Beer'),
('Alternative Sugar Beer'),
('Classic Style Smoked Beer'),
('Specialty Smoked Beer'),
('Wood-Aged Beer'),
('Specialty Wood-Aged Beer'),
('Clone Beer'),
('Mixed-Style Beer'),
('Experimental Beer')
;