/* Migration Script */
 
GO
INSERT INTO [dbo].[Breweries] ([Name]) VALUES
(N'Browar Ciechan'),
(N'Browar Lwówek'),
(N'Browar Bojanowo'),
(N'Browar Tenczynek'),
(N'Browar Biskupiec'),
(N'Browar Bosman'),
(N'Browar Kasztelan'),
(N'Browar Okocim'),
(N'Browar Dojlidy'),
(N'Browar Książęcy'),
(N'Browar Lech'),
(N'Browary Górnośląskie'),
(N'Browar Jędrzejów'),
(N'Browar BROK w Koszalinie'),
(N'Browar Łomża'),
(N'Browar Van Pur'),
(N'Browar Bracki'),
(N'Browar Elbląg'),
(N'Browar Leżajsk'),
(N'Browar Warka'),
(N'Browar Żywiec'),
(N'Browar Amber'),
(N'Browar Bartek'),
(N'Browar Bazyliszek'),
(N'Browar Bednary'),
(N'Browarnia'),
(N'Browar Cornelius'),
(N'Browar Czarnków'),
(N'Browar EDI'),
(N'Browar Fortuna'),
(N'Browar Fuhrmann'),
(N'Browar Głubczyce'),
(N'Browar Gościszewo'),
(N'Browar w Grodzisku Wielkopolskim'),
(N'Browar Grybów'),
(N'Browar Imielin'),
(N'Browar Jabłonowo'),
(N'Browar Jagiełło'),
(N'Browar Koreb'),
(N'Browar Kormoran'),
(N'Browar Krajan'),
(N'Browar na Jurze'),
(N'Browar Namysłów'),
(N'Browar Nr 1'),
(N'Pracownia Piwa'),
(N'Browar Probus'),
(N'Browar Srokowski'),
(N'Browar Stu Mostów'),
(N'Browar Tarczyn'),
(N'Browar Ursa Maior'),
(N'Browar Wąsosz'),
(N'Browar Witnica'),
(N'Browar Zamkowy'),
(N'Browar Zarzecze'),
(N'Browar Zodiak'),
(N'Browar w Zwierzyńcu')
;